/* This file was generated by SableCC (http://www.sablecc.org/). */

package MiniLangCompiler.node;

import MiniLangCompiler.analysis.*;

@SuppressWarnings("nls")
public final class ACstMultFactor extends PFactor
{
    private PFactor _factor_;
    private TStar _star_;
    private PSterm _sterm_;

    public ACstMultFactor()
    {
        // Constructor
    }

    public ACstMultFactor(
        @SuppressWarnings("hiding") PFactor _factor_,
        @SuppressWarnings("hiding") TStar _star_,
        @SuppressWarnings("hiding") PSterm _sterm_)
    {
        // Constructor
        setFactor(_factor_);

        setStar(_star_);

        setSterm(_sterm_);

    }

    @Override
    public Object clone()
    {
        return new ACstMultFactor(
            cloneNode(this._factor_),
            cloneNode(this._star_),
            cloneNode(this._sterm_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACstMultFactor(this);
    }

    public PFactor getFactor()
    {
        return this._factor_;
    }

    public void setFactor(PFactor node)
    {
        if(this._factor_ != null)
        {
            this._factor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._factor_ = node;
    }

    public TStar getStar()
    {
        return this._star_;
    }

    public void setStar(TStar node)
    {
        if(this._star_ != null)
        {
            this._star_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._star_ = node;
    }

    public PSterm getSterm()
    {
        return this._sterm_;
    }

    public void setSterm(PSterm node)
    {
        if(this._sterm_ != null)
        {
            this._sterm_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sterm_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._factor_)
            + toString(this._star_)
            + toString(this._sterm_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._factor_ == child)
        {
            this._factor_ = null;
            return;
        }

        if(this._star_ == child)
        {
            this._star_ = null;
            return;
        }

        if(this._sterm_ == child)
        {
            this._sterm_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._factor_ == oldChild)
        {
            setFactor((PFactor) newChild);
            return;
        }

        if(this._star_ == oldChild)
        {
            setStar((TStar) newChild);
            return;
        }

        if(this._sterm_ == oldChild)
        {
            setSterm((PSterm) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
