/* This file was generated by SableCC (http://www.sablecc.org/). */

package MiniLangCompiler.node;

import MiniLangCompiler.analysis.*;

@SuppressWarnings("nls")
public final class ACstDivdFactor extends PFactor
{
    private PFactor _factor_;
    private TSlash _slash_;
    private PSterm _sterm_;

    public ACstDivdFactor()
    {
        // Constructor
    }

    public ACstDivdFactor(
        @SuppressWarnings("hiding") PFactor _factor_,
        @SuppressWarnings("hiding") TSlash _slash_,
        @SuppressWarnings("hiding") PSterm _sterm_)
    {
        // Constructor
        setFactor(_factor_);

        setSlash(_slash_);

        setSterm(_sterm_);

    }

    @Override
    public Object clone()
    {
        return new ACstDivdFactor(
            cloneNode(this._factor_),
            cloneNode(this._slash_),
            cloneNode(this._sterm_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACstDivdFactor(this);
    }

    public PFactor getFactor()
    {
        return this._factor_;
    }

    public void setFactor(PFactor node)
    {
        if(this._factor_ != null)
        {
            this._factor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._factor_ = node;
    }

    public TSlash getSlash()
    {
        return this._slash_;
    }

    public void setSlash(TSlash node)
    {
        if(this._slash_ != null)
        {
            this._slash_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._slash_ = node;
    }

    public PSterm getSterm()
    {
        return this._sterm_;
    }

    public void setSterm(PSterm node)
    {
        if(this._sterm_ != null)
        {
            this._sterm_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sterm_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._factor_)
            + toString(this._slash_)
            + toString(this._sterm_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._factor_ == child)
        {
            this._factor_ = null;
            return;
        }

        if(this._slash_ == child)
        {
            this._slash_ = null;
            return;
        }

        if(this._sterm_ == child)
        {
            this._sterm_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._factor_ == oldChild)
        {
            setFactor((PFactor) newChild);
            return;
        }

        if(this._slash_ == oldChild)
        {
            setSlash((TSlash) newChild);
            return;
        }

        if(this._sterm_ == oldChild)
        {
            setSterm((PSterm) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
