/* This file was generated by SableCC (http://www.sablecc.org/). */

package MiniLangCompiler.node;

import java.util.*;
import MiniLangCompiler.analysis.*;

@SuppressWarnings("nls")
public final class AIfElseStatement extends PStatement
{
    private TIf _if_;
    private PCstExp _cstExp_;
    private TThen _then_;
    private final LinkedList<PStatement> _statement_ = new LinkedList<PStatement>();
    private TElse _else_;
    private final LinkedList<PStatement> _elseStmts_ = new LinkedList<PStatement>();
    private TEndif _endif_;

    public AIfElseStatement()
    {
        // Constructor
    }

    public AIfElseStatement(
        @SuppressWarnings("hiding") TIf _if_,
        @SuppressWarnings("hiding") PCstExp _cstExp_,
        @SuppressWarnings("hiding") TThen _then_,
        @SuppressWarnings("hiding") List<?> _statement_,
        @SuppressWarnings("hiding") TElse _else_,
        @SuppressWarnings("hiding") List<?> _elseStmts_,
        @SuppressWarnings("hiding") TEndif _endif_)
    {
        // Constructor
        setIf(_if_);

        setCstExp(_cstExp_);

        setThen(_then_);

        setStatement(_statement_);

        setElse(_else_);

        setElseStmts(_elseStmts_);

        setEndif(_endif_);

    }

    @Override
    public Object clone()
    {
        return new AIfElseStatement(
            cloneNode(this._if_),
            cloneNode(this._cstExp_),
            cloneNode(this._then_),
            cloneList(this._statement_),
            cloneNode(this._else_),
            cloneList(this._elseStmts_),
            cloneNode(this._endif_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIfElseStatement(this);
    }

    public TIf getIf()
    {
        return this._if_;
    }

    public void setIf(TIf node)
    {
        if(this._if_ != null)
        {
            this._if_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._if_ = node;
    }

    public PCstExp getCstExp()
    {
        return this._cstExp_;
    }

    public void setCstExp(PCstExp node)
    {
        if(this._cstExp_ != null)
        {
            this._cstExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cstExp_ = node;
    }

    public TThen getThen()
    {
        return this._then_;
    }

    public void setThen(TThen node)
    {
        if(this._then_ != null)
        {
            this._then_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._then_ = node;
    }

    public LinkedList<PStatement> getStatement()
    {
        return this._statement_;
    }

    public void setStatement(List<?> list)
    {
        for(PStatement e : this._statement_)
        {
            e.parent(null);
        }
        this._statement_.clear();

        for(Object obj_e : list)
        {
            PStatement e = (PStatement) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._statement_.add(e);
        }
    }

    public TElse getElse()
    {
        return this._else_;
    }

    public void setElse(TElse node)
    {
        if(this._else_ != null)
        {
            this._else_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._else_ = node;
    }

    public LinkedList<PStatement> getElseStmts()
    {
        return this._elseStmts_;
    }

    public void setElseStmts(List<?> list)
    {
        for(PStatement e : this._elseStmts_)
        {
            e.parent(null);
        }
        this._elseStmts_.clear();

        for(Object obj_e : list)
        {
            PStatement e = (PStatement) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._elseStmts_.add(e);
        }
    }

    public TEndif getEndif()
    {
        return this._endif_;
    }

    public void setEndif(TEndif node)
    {
        if(this._endif_ != null)
        {
            this._endif_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._endif_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._if_)
            + toString(this._cstExp_)
            + toString(this._then_)
            + toString(this._statement_)
            + toString(this._else_)
            + toString(this._elseStmts_)
            + toString(this._endif_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._if_ == child)
        {
            this._if_ = null;
            return;
        }

        if(this._cstExp_ == child)
        {
            this._cstExp_ = null;
            return;
        }

        if(this._then_ == child)
        {
            this._then_ = null;
            return;
        }

        if(this._statement_.remove(child))
        {
            return;
        }

        if(this._else_ == child)
        {
            this._else_ = null;
            return;
        }

        if(this._elseStmts_.remove(child))
        {
            return;
        }

        if(this._endif_ == child)
        {
            this._endif_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._if_ == oldChild)
        {
            setIf((TIf) newChild);
            return;
        }

        if(this._cstExp_ == oldChild)
        {
            setCstExp((PCstExp) newChild);
            return;
        }

        if(this._then_ == oldChild)
        {
            setThen((TThen) newChild);
            return;
        }

        for(ListIterator<PStatement> i = this._statement_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PStatement) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._else_ == oldChild)
        {
            setElse((TElse) newChild);
            return;
        }

        for(ListIterator<PStatement> i = this._elseStmts_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PStatement) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._endif_ == oldChild)
        {
            setEndif((TEndif) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
