/* This file was generated by SableCC (http://www.sablecc.org/). */

package MiniLangCompiler.node;

import java.util.*;
import MiniLangCompiler.analysis.*;

@SuppressWarnings("nls")
public final class AProgramProg extends PProg
{
    private final LinkedList<PDecl> _d_ = new LinkedList<PDecl>();
    private final LinkedList<PStmt> _s_ = new LinkedList<PStmt>();

    public AProgramProg()
    {
        // Constructor
    }

    public AProgramProg(
        @SuppressWarnings("hiding") List<?> _d_,
        @SuppressWarnings("hiding") List<?> _s_)
    {
        // Constructor
        setD(_d_);

        setS(_s_);

    }

    @Override
    public Object clone()
    {
        return new AProgramProg(
            cloneList(this._d_),
            cloneList(this._s_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAProgramProg(this);
    }

    public LinkedList<PDecl> getD()
    {
        return this._d_;
    }

    public void setD(List<?> list)
    {
        for(PDecl e : this._d_)
        {
            e.parent(null);
        }
        this._d_.clear();

        for(Object obj_e : list)
        {
            PDecl e = (PDecl) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._d_.add(e);
        }
    }

    public LinkedList<PStmt> getS()
    {
        return this._s_;
    }

    public void setS(List<?> list)
    {
        for(PStmt e : this._s_)
        {
            e.parent(null);
        }
        this._s_.clear();

        for(Object obj_e : list)
        {
            PStmt e = (PStmt) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._s_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._d_)
            + toString(this._s_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._d_.remove(child))
        {
            return;
        }

        if(this._s_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PDecl> i = this._d_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PDecl) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        for(ListIterator<PStmt> i = this._s_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PStmt) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
