/* This file was generated by SableCC (http://www.sablecc.org/). */

package MiniLangCompiler.node;

import MiniLangCompiler.analysis.*;

@SuppressWarnings("nls")
public final class AStermSterm extends PSterm
{
    private TMinus _minus_;
    private PSterm _sterm_;

    public AStermSterm()
    {
        // Constructor
    }

    public AStermSterm(
        @SuppressWarnings("hiding") TMinus _minus_,
        @SuppressWarnings("hiding") PSterm _sterm_)
    {
        // Constructor
        setMinus(_minus_);

        setSterm(_sterm_);

    }

    @Override
    public Object clone()
    {
        return new AStermSterm(
            cloneNode(this._minus_),
            cloneNode(this._sterm_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStermSterm(this);
    }

    public TMinus getMinus()
    {
        return this._minus_;
    }

    public void setMinus(TMinus node)
    {
        if(this._minus_ != null)
        {
            this._minus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._minus_ = node;
    }

    public PSterm getSterm()
    {
        return this._sterm_;
    }

    public void setSterm(PSterm node)
    {
        if(this._sterm_ != null)
        {
            this._sterm_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sterm_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._minus_)
            + toString(this._sterm_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._minus_ == child)
        {
            this._minus_ = null;
            return;
        }

        if(this._sterm_ == child)
        {
            this._sterm_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._minus_ == oldChild)
        {
            setMinus((TMinus) newChild);
            return;
        }

        if(this._sterm_ == oldChild)
        {
            setSterm((PSterm) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
