/* This file was generated by SableCC (http://www.sablecc.org/). */

package MiniLangCompiler.node;

import MiniLangCompiler.analysis.*;

@SuppressWarnings("nls")
public final class ATermFactor extends PFactor
{
    private PSterm _sterm_;

    public ATermFactor()
    {
        // Constructor
    }

    public ATermFactor(
        @SuppressWarnings("hiding") PSterm _sterm_)
    {
        // Constructor
        setSterm(_sterm_);

    }

    @Override
    public Object clone()
    {
        return new ATermFactor(
            cloneNode(this._sterm_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATermFactor(this);
    }

    public PSterm getSterm()
    {
        return this._sterm_;
    }

    public void setSterm(PSterm node)
    {
        if(this._sterm_ != null)
        {
            this._sterm_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sterm_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._sterm_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._sterm_ == child)
        {
            this._sterm_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._sterm_ == oldChild)
        {
            setSterm((PSterm) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
